### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by EnricoSx** [Gozem/am2320#1]
root@claudia:/home/pi/am2320# ./am2320.py
Traceback (most recent call last):
  File "./am2320.py", line 86, in <module>
    (t,h) = am2320.readSensor()
  File "./am2320.py", line 46, in readSensor
    posix.write(fd, b'\x03\x00\x04')
OSError: [Errno 5] Input/output error

**Comment by Gozem** [comment]
Your sensor is not properly connected or somethings wrong with your I2C bus.

**Comment by EnricoSx** [comment]
Can you tell me correct pin connection?

**Comment by EnricoSx** [comment]
sudo i2cdetect -y 1 find my sensor 5c

**Comment by Gozem** [comment]
You need to run it as root. Have i2c enabled in raspberry config.
Pins are 3 and 5: http://www.raspberrypi-spy.co.uk/2012/06/simple-guide-to-the-rpi-gpio-header-and-pins/#prettyPhoto/0/

But you seems to be correct if i2cdetect works. You should be needing to run i2cdetect twice in short period in order to find it. AM2320 is in sleep mode and first read from it will only wake it up and it won't respond.

Otherwise I don't know why it isn't working for you. Tried the .c version i have? Compile it using the run.sh-script.

**Comment by EnricoSx** [comment]
Raspian lite missing some component?

**Comment by EnricoSx** [comment]
I reinstall raspian and works, thanks
